
name: Rodar Bot de Apostas

on:
  schedule:
    - cron: '0 8 * * *'  # Executa todos os dias às 5h da manhã no horário de Brasília


jobs:
  run-script:
    runs-on: ubuntu-latest  # Usando o Ubuntu como sistema operacional

    steps:
      - name: Checar o repositório
        uses: actions/checkout@v2

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests schedule

      - name: Rodar o bot de apostas
        run: python bot_apostas.py

